Repository spothings/strip-table, pull requests merged in 2023-05, with the labels that each got.

#1 fix LDR sensor
  doc/readme.md
  img/readme.md
  img/strip_table_view.jpg
  readme.md
  src/main/.gitignore
  src/main/built-in-led.ino
  src/main/ldr.ino
  src/main/main.ino
  src/main/relay.ino
  src/main/serial-monitor.ino
  src/main/wifi.ino
  src/project-name/lib/sample-sensor.h
  src/project-name/project-name.ino
Labels: enhancement

#2 reset counter
  doc/readme.md
  readme.md
  src/main/built-in-led.ino
  src/main/ldr.ino
  src/main/main.ino
  src/main/relay.ino
  src/main/serial-monitor.ino
Labels: enhancement

#3 setup colaboration
  src/main/main.ino
  src/main/secret.ino.example
Labels: documentation, enhancement, help wanted

#6 add sch and pcb
  pcb/Autorouter_pcb_2023-05-29.dsn
  pcb/Gerber_pcb_2023-05-29.zip
  pcb/Gerber_pcb_2023-05-29/Drill_PTH_Through.DRL
  pcb/Gerber_pcb_2023-05-29/Drill_PTH_Through_Via.DRL
  pcb/Gerber_pcb_2023-05-29/Gerber_BoardOutlineLayer.GKO
  pcb/Gerber_pcb_2023-05-29/Gerber_BottomLayer.GBL
  pcb/Gerber_pcb_2023-05-29/Gerber_BottomSolderMaskLayer.GBS
  pcb/Gerber_pcb_2023-05-29/Gerber_TopLayer.GTL
  pcb/Gerber_pcb_2023-05-29/Gerber_TopSilkscreenLayer.GTO
  pcb/Gerber_pcb_2023-05-29/Gerber_TopSolderMaskLayer.GTS
  pcb/Gerber_pcb_2023-05-29/How-to-order-PCB.txt
  pcb/OBJ_pcb_2023-05-29.zip
  pcb/OBJ_pcb_2023-05-29/OBJ_pcb.mtl
  pcb/OBJ_pcb_2023-05-29/OBJ_pcb.obj
  pcb/PCB_pcb_2023-05-29.json
  pcb/PCB_pcb_2023-05-29.pdf
  pcb/PCB_pcb_2023-05-29.png
  pcb/PCB_pcb_2023-05-29.svg
  pcb/pcb_2023-05-29.dxf
  pcb/pcb_2023-05-29.pcbdoc
  pcb/pcb_2023-05-29.svg
  pcb/readme.md
  sch/SCH_strip-table_2023-05-29.json
  sch/Schematic_strip-table_2023-05-29.pdf
  sch/Schematic_strip-table_2023-05-29.png
  sch/Schematic_strip-table_2023-05-29.svg
  sch/sch_2023-05-29.schdoc
  sch/sch_2023-05-29.svg
Labels: good first issue

#7 add timeNTP
  src/main/main.ino
  src/main/ntpTime.ino
Labels: good first issue

#8 implement NTP time
  src/main/ldr.ino
  src/main/main.ino
  src/main/ntpTime.ino
  src/main/relay.ino
  src/main/serial-monitor.ino
Labels: enhancement
